openapi: 3.0.3

info:
  title: API ドキュメント
  description: docker-nuxt-laravelサンプルのAPIドキュメント
  version: "0.0.0"

servers:
  - url: http://localhost:80/api
    description: docker local

paths:
  '/':
    get:
      responses:
        '200':
          description: 'OK'
